# Generated by Django 4.2.7 on 2024-05-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stApp', '0002_course_department_teacher_student_course_dept'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Batch',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='course',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='batch',
        ),
    ]
