# Generated by Django 4.2.7 on 2024-05-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stApp', '0003_rename_course_batch_rename_course_batch_batch_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batch',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='batch',
            new_name='course',
        ),
    ]
