# Generated by Django 4.2.7 on 2024-05-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stApp', '0004_rename_batch_course_rename_batch_course_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='batch',
            new_name='course',
        ),
    ]
