# Generated by Django 4.2 on 2024-05-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stApp', '0005_rename_batch_student_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
