# Generated by Django 6.0.1 on 2026-02-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
