# Generated by Django 5.1.4 on 2026-02-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0002_remove_customer_address_remove_customer_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
