# Generated by Django 5.1.4 on 2026-02-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0006_governmentofficer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedFertiliser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='seeds_fertilisers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_app.governmentofficer')),
            ],
        ),
    ]
