# Generated by Django 5.1.4 on 2026-02-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0007_seedfertiliser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeedFertiliser',
        ),
    ]
