# Generated by Django 5.1.4 on 2026-02-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0009_seedfertiliser'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedfertiliser',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
