# Generated by Django 5.1.4 on 2026-02-14 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0010_seedfertiliser_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='cart', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_app.farmer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_app.seedfertiliser')),
            ],
        ),
    ]
