# Generated by Django 5.1.4 on 2026-02-16 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0012_deliveryboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmercart',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crop_app.deliveryboy'),
        ),
    ]
