# Generated by Django 5.1.6 on 2026-02-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0015_productcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='status',
            field=models.CharField(default='pending', max_length=20, null=True),
        ),
    ]
