# Generated by Django 5.1.6 on 2026-02-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0017_productorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
