# Generated by Django 5.1.6 on 2026-02-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0018_delete_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crop_app.deliveryboy'),
        ),
    ]
