# Generated by Django 5.1.6 on 2026-02-18 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0019_productcart_delivery_boy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_app.buyer')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_app.productcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_app.product')),
            ],
        ),
    ]
