# Generated by Django 5.1.6 on 2026-02-18 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0020_productfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedFertiliserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_app.farmer')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crop_app.farmercart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_app.seedfertiliser')),
            ],
        ),
    ]
