# Generated by Django 5.1.6 on 2026-02-18 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0021_seedfertiliserfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerOfficerChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.CharField(max_length=50)),
                ('sender_type', models.CharField(max_length=20)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_app.farmer')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_app.governmentofficer')),
            ],
        ),
    ]
