# Generated by Django 5.1.6 on 2026-02-18 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0022_farmerofficerchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='farming_alerts/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='farming_alerts/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_app.governmentofficer')),
            ],
        ),
    ]
