# Generated by Django 5.1.6 on 2026-03-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0023_farmingalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_images/'),
        ),
    ]
