# Generated by Django 5.1.2 on 2024-10-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedexpense',
            old_name='pay_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='fixedexpense',
            name='salary_amount',
        ),
    ]
