# Generated by Django 5.1.2 on 2024-10-28 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_pay_amount_fixedexpense_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadbill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('bill_receipt', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('addedDate', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.CharField(choices=[('one-time', 'One-time'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userreg')),
            ],
        ),
    ]
