# Generated by Django 5.0.7 on 2025-03-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_uploadbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
