# Generated by Django 5.0.7 on 2025-03-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_userreg_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedexpense',
            name='year',
        ),
    ]
