# Generated by Django 5.0.7 on 2025-03-05 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_advocate_advo_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_request',
            name='requested_advocate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_advocate', to='myapp.advocate'),
        ),
    ]
