# Generated by Django 5.0.7 on 2025-03-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_case_request_requested_advocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_request',
            name='user_uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='case_files'),
        ),
    ]
