# Generated by Django 5.0.7 on 2025-03-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_case_request_user_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_request',
            name='user_uploaded_file',
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='myapp.case_request')),
            ],
        ),
    ]
