# Generated by Django 5.0.7 on 2025-03-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_case_request_user_uploaded_file_casefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='text',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
