# Generated by Django 5.1.6 on 2026-04-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rating_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_request',
            name='date',
        ),
    ]
