# Generated by Django 5.1.6 on 2026-04-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_case_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_request',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
