# Generated by Django 5.1.4 on 2026-02-03 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0009_alter_slots_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTestBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('amount', models.IntegerField(default=500)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('booking_status', models.CharField(default='Booked', max_length=20)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.labreg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.userreg')),
            ],
        ),
        migrations.CreateModel(
            name='BloodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WBC', models.FloatField()),
                ('RBC', models.FloatField()),
                ('HGB', models.FloatField()),
                ('PLT', models.FloatField()),
                ('NEUT', models.FloatField()),
                ('LYMPH', models.FloatField()),
                ('MONO', models.FloatField()),
                ('EOS', models.FloatField()),
                ('BASO', models.FloatField()),
                ('disease', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.bloodtestbooking')),
            ],
        ),
    ]
