# Generated by Django 5.1.4 on 2026-02-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0010_bloodtestbooking_bloodreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='BloodReport',
        ),
        migrations.DeleteModel(
            name='BloodTestBooking',
        ),
    ]
