# Generated by Django 5.1.4 on 2026-02-03 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0011_remove_bloodtestbooking_lab_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WBC', models.FloatField()),
                ('RBC', models.FloatField()),
                ('HGB', models.FloatField()),
                ('PLT', models.FloatField()),
                ('NEUT', models.FloatField()),
                ('LYMPH', models.FloatField()),
                ('MONO', models.FloatField()),
                ('EOS', models.FloatField()),
                ('BASO', models.FloatField()),
                ('Disease', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
