# Generated by Django 5.1.4 on 2026-02-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0012_bloodtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodTest',
        ),
    ]
