# Generated by Django 5.1.4 on 2026-02-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0013_delete_bloodtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WBC', models.FloatField()),
                ('RBC', models.FloatField()),
                ('HGB', models.FloatField()),
                ('PLT', models.FloatField()),
                ('NEUT', models.FloatField()),
                ('LYMPH', models.FloatField()),
                ('MONO', models.FloatField()),
                ('EOS', models.FloatField()),
                ('BASO', models.FloatField()),
                ('predicted_disease', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
