# Generated by Django 5.1.4 on 2026-02-03 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0015_delete_bloodtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTestBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.labreg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.userreg')),
            ],
        ),
        migrations.CreateModel(
            name='BloodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WBC', models.FloatField()),
                ('RBC', models.FloatField()),
                ('HGB', models.FloatField()),
                ('PLT', models.FloatField()),
                ('NEUT', models.FloatField()),
                ('LYMPH', models.FloatField()),
                ('MONO', models.FloatField()),
                ('EOS', models.FloatField()),
                ('BASO', models.FloatField()),
                ('predicted_disease', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='blood_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.bloodtestbooking')),
            ],
        ),
        migrations.CreateModel(
            name='BloodPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Successful', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.bloodtestbooking')),
            ],
        ),
    ]
