# Generated by Django 5.1.4 on 2026-02-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0016_bloodtestbooking_bloodreport_bloodpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.IntegerField(default=0)),
                ('bloodreport', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.labreg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.userreg')),
            ],
        ),
    ]
