# Generated by Django 5.1.4 on 2026-02-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0017_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodreport',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='BloodPayment',
        ),
        migrations.DeleteModel(
            name='BloodReport',
        ),
        migrations.DeleteModel(
            name='BloodTestBooking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
