# Generated by Django 5.1.4 on 2026-02-04 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0018_remove_bloodreport_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTestBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(default='Blood Test', max_length=100)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.labreg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EdiagApp.userreg')),
            ],
        ),
    ]
