# Generated by Django 5.1.4 on 2026-02-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0019_bloodtestbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtestbooking',
            name='baso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodtestbooking',
            name='eos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodtestbooking',
            name='hgb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodtestbooking',
            name='lymph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodtestbooking',
            name='mono',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodtestbooking',
            name='neut',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodtestbooking',
            name='plt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodtestbooking',
            name='predicted_disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloodtestbooking',
            name='rbc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodtestbooking',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='blood_reports/'),
        ),
        migrations.AddField(
            model_name='bloodtestbooking',
            name='wbc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
