# Generated by Django 5.1.4 on 2026-02-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0020_bloodtestbooking_baso_bloodtestbooking_eos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='baso',
        ),
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='eos',
        ),
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='hgb',
        ),
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='lymph',
        ),
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='mono',
        ),
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='neut',
        ),
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='plt',
        ),
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='predicted_disease',
        ),
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='rbc',
        ),
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='report_pdf',
        ),
        migrations.RemoveField(
            model_name='bloodtestbooking',
            name='wbc',
        ),
    ]
