# Generated by Django 5.1.4 on 2026-02-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0021_remove_bloodtestbooking_baso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtestbooking',
            name='pdf_report',
            field=models.FileField(null=True, upload_to='pdf_reports/'),
        ),
        migrations.AddField(
            model_name='bloodtestbooking',
            name='predicted_disease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloodtestbooking',
            name='report_file',
            field=models.FileField(null=True, upload_to='reports/'),
        ),
    ]
