# Generated by Django 5.1.4 on 2026-02-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0022_bloodtestbooking_pdf_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtestbooking',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to='pdf_reports/'),
        ),
    ]
