# Generated by Django 5.1.6 on 2026-03-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0023_alter_bloodtestbooking_pdf_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreg',
            name='pwd',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='pwd',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
