# Generated by Django 5.1.4 on 2024-12-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='user_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
