# Generated by Django 5.1.4 on 2024-12-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_login_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
