# Generated by Django 5.1.4 on 2024-12-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='premium_date',
            field=models.DateField(null=True),
        ),
    ]
