# Generated by Django 5.1.4 on 2024-12-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_login_premium_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='question',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
