# Generated by Django 5.1.4 on 2024-12-30 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_user_loginid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=700)),
                ('summary', models.CharField(max_length=700)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.user')),
            ],
        ),
        migrations.CreateModel(
            name='Video_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('summary', models.CharField(max_length=700)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.user')),
            ],
        ),
    ]
