# Generated by Django 5.1.4 on 2024-12-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0008_text_history_video_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text_history',
            old_name='input',
            new_name='text_input',
        ),
    ]
