# Generated by Django 5.1.4 on 2024-12-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0009_rename_input_text_history_text_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_history',
            name='video',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
