# Generated by Django 5.1.4 on 2024-12-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
