# Generated by Django 5.1.4 on 2025-01-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0012_feedback_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.IntegerField()),
                ('real_price', models.FloatField()),
                ('offer_price', models.FloatField(null=True)),
                ('offer_started', models.DateTimeField(auto_now_add=True)),
                ('offer_till', models.DateTimeField(null=True)),
            ],
        ),
    ]
