# Generated by Django 5.1.6 on 2025-03-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0013_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
