# Generated by Django 5.1.4 on 2025-01-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
