# Generated by Django 5.1.4 on 2025-01-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
