# Generated by Django 5.0.7 on 2025-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_payment_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
