# Generated by Django 5.2.9 on 2026-07-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_club_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club_manager',
            name='status',
        ),
    ]
