# Generated by Django 5.2.9 on 2026-07-18 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_scout'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformancePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=30)),
                ('overall_rating', models.FloatField()),
                ('predicted_rating', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.scout')),
            ],
        ),
    ]
