# Generated by Django 5.2.9 on 2026-07-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_performanceprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceprediction',
            name='assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceprediction',
            name='club',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='performanceprediction',
            name='defending',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceprediction',
            name='dribbling',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceprediction',
            name='goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceprediction',
            name='market_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceprediction',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='performanceprediction',
            name='pace',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceprediction',
            name='passing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceprediction',
            name='physical',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceprediction',
            name='potential',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceprediction',
            name='shooting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanceprediction',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanceprediction',
            name='overall_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanceprediction',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='performanceprediction',
            name='predicted_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
