# Generated by Django 5.2.9 on 2026-07-20 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_performanceprediction_assists_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarPlayerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_player', models.CharField(max_length=100)),
                ('recommended_player', models.CharField(max_length=100)),
                ('recommended_club', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=20)),
                ('overall_rating', models.FloatField()),
                ('market_value', models.BigIntegerField()),
                ('recommendation_date', models.DateTimeField(auto_now_add=True)),
                ('club_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.club_manager')),
            ],
            options={
                'unique_together': {('club_manager', 'selected_player', 'recommended_player')},
            },
        ),
    ]
