# Generated by Django 5.2.9 on 2026-07-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0007_similarplayerrecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimilarPlayerRecommendation',
        ),
    ]
