# Generated by Django 5.2.9 on 2026-07-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0009_similarplayerrecommendation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='similarplayerrecommendation',
            unique_together={('club_manager', 'selected_player')},
        ),
        migrations.RemoveField(
            model_name='similarplayerrecommendation',
            name='recommended_player',
        ),
    ]
