# Generated by Django 5.2.9 on 2026-07-20 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0010_alter_similarplayerrecommendation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('max_age', models.IntegerField()),
                ('minimum_rating', models.FloatField()),
                ('maximum_budget', models.BigIntegerField()),
                ('recommendation_date', models.DateTimeField(auto_now_add=True)),
                ('club_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.club_manager')),
            ],
            options={
                'ordering': ['-recommendation_date'],
            },
        ),
    ]
