# Generated by Django 5.2.9 on 2026-07-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0011_recruitmentrecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecruitmentRecommendation',
        ),
    ]
