# Generated by Django 5.2.9 on 2026-07-20 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0012_delete_recruitmentrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('max_age', models.IntegerField()),
                ('min_rating', models.IntegerField()),
                ('recommendation_date', models.DateTimeField(auto_now_add=True)),
                ('club_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.club_manager')),
            ],
            options={
                'unique_together': {('club_manager', 'position', 'max_age', 'min_rating')},
            },
        ),
    ]
