# Generated by Django 5.2.15 on 2026-06-27 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage_app', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('assessor_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='insurance_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
