# Generated by Django 5.2.15 on 2026-06-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage_app', '0006_damagerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DamageRequest',
        ),
    ]
