# Generated by Django 5.2.15 on 2026-06-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage_app', '0008_claim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
