# Generated by Django 5.2.15 on 2026-07-04 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegfru_app', '0003_store_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspection_images/')),
                ('predicted_class', models.CharField(choices=[('Fresh Apple', 'Fresh Apple'), ('Fresh Banana', 'Fresh Banana'), ('Fresh Orange', 'Fresh Orange'), ('Rotten Apple', 'Rotten Apple'), ('Rotten Banana', 'Rotten Banana'), ('Rotten Orange', 'Rotten Orange')], max_length=50)),
                ('freshness', models.CharField(choices=[('Fresh', 'Fresh'), ('Rotten', 'Rotten')], max_length=20)),
                ('confidence', models.FloatField()),
                ('verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegfru_app.quality_inspector')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=30, unique=True)),
                ('remarks', models.TextField()),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vegfru_app.predictionhistory')),
            ],
        ),
    ]
