# Generated by Django 5.2.15 on 2026-07-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegfru_app', '0004_predictionhistory_inspectionreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InspectionReport',
        ),
    ]
