# Generated by Django 5.2.15 on 2026-07-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegfru_app', '0007_delete_inspectionreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='verified',
        ),
    ]
