# Generated by Django 5.2.15 on 2026-07-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegfru_app', '0008_remove_predictionhistory_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
