# Generated by Django 5.2.15 on 2026-07-06 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegfru_app', '0009_predictionhistory_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegfru_app.store_manager'),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
