# Generated by Django 5.1.7 on 2025-03-29 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0007_delete_worker_allocation_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AtmDeposits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer_request',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customer_request',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment_of_contractor',
            name='customer_req',
        ),
        migrations.RemoveField(
            model_name='request_feedback',
            name='Customer_request',
        ),
        migrations.RemoveField(
            model_name='worker_allocation',
            name='customer_request',
        ),
        migrations.RemoveField(
            model_name='payment_of_worker',
            name='worker_allocation',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='worker_allocation',
            name='worker',
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='update_cou',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_image',
            field=models.ImageField(null=True, upload_to='verification_images'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Atm_card_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('branch_status', models.CharField(default='Pending', max_length=50)),
                ('admin_status', models.CharField(default='Pending', max_length=50)),
                ('cardno', models.CharField(max_length=16, null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('cvv', models.CharField(max_length=3, null=True)),
                ('pin', models.CharField(max_length=4, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('pin_change_date', models.DateTimeField(null=True)),
                ('card_issue_date', models.DateTimeField(null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AtmWithdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('withdrawer_photo', models.ImageField(null=True, upload_to='withdrawer_photos')),
                ('atmcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buidingFaciliSysApp.atm_card_request')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeposits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='payment_of_contractor',
        ),
        migrations.DeleteModel(
            name='Request_feedback',
        ),
        migrations.DeleteModel(
            name='Customer_request',
        ),
        migrations.DeleteModel(
            name='payment_of_worker',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.DeleteModel(
            name='Worker_allocation',
        ),
    ]
