# Generated by Django 5.1.7 on 2025-03-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0008_atm_atmdeposits_remove_customer_request_contractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
