# Generated by Django 5.1.7 on 2025-04-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0009_alter_customuser_verification_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atm_card_request',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='atm_card_request',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='atm_card_request',
            name='pin_change_date',
        ),
    ]
