# Generated by Django 5.1.7 on 2025-04-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0010_remove_atm_card_request_added_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AtmWithdrawals',
            new_name='UserWithdrawals',
        ),
        migrations.DeleteModel(
            name='Atm',
        ),
        migrations.DeleteModel(
            name='AtmDeposits',
        ),
    ]
