# Generated by Django 4.2.7 on 2025-04-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgtoimgenc',
            name='key',
            field=models.FileField(null=True, upload_to='img_to_img_enc/'),
        ),
        migrations.AlterField(
            model_name='imgtoimgenc',
            name='output',
            field=models.FileField(null=True, upload_to='img_to_img_enc/'),
        ),
    ]
