# Generated by Django 4.2.7 on 2025-04-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uceApp', '0002_alter_imgtoimgenc_key_alter_imgtoimgenc_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgToImgDec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='img_to_img_enc/')),
                ('key', models.FileField(null=True, upload_to='img_to_img_enc/')),
            ],
        ),
    ]
