# Generated by Django 4.2.7 on 2025-04-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uceApp', '0004_alter_encodedtext_encodeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='encodedtext',
            name='inputImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
