# Generated by Django 4.2.7 on 2025-04-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uceApp', '0005_encodedtext_inputimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncodedTextDec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='img_to_img_enc/')),
            ],
        ),
    ]
