# Generated by Django 5.1.2 on 2024-10-21 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drdApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetection',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drdApp.score'),
        ),
    ]
