# Generated by Django 5.1.2 on 2024-10-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drdApp', '0002_imagedetection_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='o3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='o4',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='s3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='s4',
        ),
    ]
