# Generated by Django 5.1.2 on 2024-11-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drdApp', '0003_remove_questions_o3_remove_questions_o4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetection',
            name='resultVal',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
