# Generated by Django 5.1.2 on 2025-04-02 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drdApp', '0004_imagedetection_resultval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('ecc_private_key', models.TextField()),
                ('ecc_public_key', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookeddate', models.DateField(auto_now_add=True)),
                ('token', models.IntegerField(blank=True, null=True)),
                ('bookingdate', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drdApp.users')),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drdApp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paydate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drdApp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_image', models.JSONField()),
                ('encrypted_diagnosis', models.JSONField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drdApp.booking')),
            ],
        ),
    ]
