# Generated by Django 5.1.2 on 2025-04-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drdApp', '0005_doctor_booking_payment_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='ecc_private_key',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='ecc_public_key',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='encrypted_diagnosis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='encrypted_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
