# Generated by Django 5.1.2 on 2025-04-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drdApp', '0006_remove_doctor_ecc_private_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='encrypted_diagnosis',
            new_name='diagnosis',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='encrypted_image',
            new_name='image',
        ),
    ]
