# Generated by Django 5.1.2 on 2025-04-04 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drdApp', '0007_rename_encrypted_diagnosis_prescription_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('sendby', models.CharField(default='admin', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drdApp.users')),
            ],
        ),
    ]
