# Generated by Django 5.1.6 on 2025-02-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
