# Generated by Django 5.1.6 on 2025-02-28 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0003_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='CART', max_length=50)),
                ('count', models.IntegerField(default=1)),
                ('book_date', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateTimeField(null=True)),
                ('total', models.IntegerField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.products')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.user')),
            ],
        ),
    ]
