# Generated by Django 5.1.6 on 2025-02-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0004_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
