# Generated by Django 5.1.6 on 2025-03-01 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0005_products_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50, null=True)),
                ('pdate', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(max_length=50, null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('message', models.CharField(max_length=500, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.bookings')),
            ],
        ),
    ]
