# Generated by Django 5.1.6 on 2025-03-01 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0006_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='boy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.delivery_boy'),
        ),
        migrations.AddField(
            model_name='delivery_boy',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
