# Generated by Django 5.1.6 on 2025-03-01 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0007_bookings_boy_delivery_boy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_boy',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.shop'),
        ),
    ]
