# Generated by Django 5.1.6 on 2025-03-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0008_delivery_boy_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_boy',
            name='status',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
    ]
