# Generated by Django 5.1.6 on 2025-03-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0009_alter_delivery_boy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('review', models.CharField(max_length=300)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.bookings')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.user')),
            ],
        ),
    ]
