# Generated by Django 5.1.6 on 2025-03-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0010_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='shop',
        ),
    ]
