# Generated by Django 5.1.6 on 2025-03-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0011_remove_feedback_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
