# Generated by Django 5.1.6 on 2025-03-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0012_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='airport',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
