# Generated by Django 5.1.6 on 2025-03-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0013_shop_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='fname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='fnumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
