# Generated by Django 5.1.6 on 2025-04-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0014_products_fname_products_fnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_boy',
            name='proof',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
