# Generated by Django 5.1.1 on 2025-04-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0015_delivery_boy_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='licence',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
