# Generated by Django 5.1.3 on 2025-07-31 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0016_shop_licence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='book',
        ),
    ]
