# Generated by Django 4.2.15 on 2026-02-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0018_shop_is_verified_shop_otp_user_age_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_boy',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery_boy',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
