# Generated by Django 4.2.15 on 2026-02-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0019_delivery_boy_is_verified_delivery_boy_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='airport',
        ),
    ]
