# Generated by Django 4.2.15 on 2026-02-10 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0020_remove_shop_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.bookings'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
