# Generated by Django 5.2.11 on 2026-03-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0021_feedback_book_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.FileField(null=True, upload_to='shop_images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
