# Generated by Django 5.2.11 on 2026-03-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0022_shop_image_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discountprice',
            field=models.IntegerField(null=True),
        ),
    ]
