# Generated by Django 5.2.11 on 2026-03-19 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0023_products_discountprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(null=True)),
                ('boy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.delivery_boy')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.shop')),
            ],
        ),
    ]
