# Generated by Django 5.2.10 on 2026-01-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='register_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
