# Generated by Django 5.2.10 on 2026-01-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
