# Generated by Django 5.2.10 on 2026-01-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
