# Generated by Django 5.2.10 on 2026-01-24 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_delete_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='semester/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.course')),
            ],
        ),
    ]
