# Generated by Django 5.2.10 on 2026-01-27 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0014_examschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_app.staff'),
        ),
    ]
