# Generated by Django 5.2.10 on 2026-01-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0016_seatallocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeatAllocation',
        ),
    ]
