# Generated by Django 5.2.10 on 2026-01-28 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0017_delete_seatallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10, null=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.hall')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.examschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.student')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.seat')),
            ],
            options={
                'unique_together': {('exam', 'seat')},
            },
        ),
    ]
