# Generated by Django 5.2.10 on 2026-01-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0018_seat_examseatallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='hall',
        ),
        migrations.DeleteModel(
            name='ExamSeatAllocation',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
