# Generated by Django 5.2.10 on 2026-01-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0020_hallseat_seatallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatallocation',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='seatallocation',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='seatallocation',
            name='student',
        ),
        migrations.DeleteModel(
            name='HallSeat',
        ),
        migrations.DeleteModel(
            name='SeatAllocation',
        ),
    ]
