# Generated by Django 5.2.10 on 2026-01-28 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0021_remove_seatallocation_seat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.examschedule')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.hall')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.student')),
            ],
            options={
                'unique_together': {('exam', 'hall', 'seat_number')},
            },
        ),
    ]
