# Generated by Django 5.1.7 on 2026-03-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0027_student_face_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='face_encoding',
        ),
    ]
