# Generated by Django 5.2.9 on 2026-05-28 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_mvd'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='uploaded_videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('prediction_result', models.CharField(blank=True, choices=[('Accident', 'Accident'), ('Non Accident', 'Non Accident')], max_length=50, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('total_frames', models.IntegerField(default=0)),
                ('accident_frames', models.IntegerField(default=0)),
                ('non_accident_frames', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('mvd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.mvd')),
            ],
        ),
    ]
