# Generated by Django 5.2.9 on 2026-05-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_accidentvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccidentVideo',
        ),
    ]
