# Generated by Django 5.2.9 on 2026-05-30 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0006_delete_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accident_predictions/')),
                ('prediction', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('mvd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_app.mvd')),
            ],
        ),
    ]
