# Generated by Django 5.2.9 on 2026-05-30 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0008_delete_accidentprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predictions/')),
                ('result', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mvd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.mvd')),
            ],
        ),
    ]
