# Generated by Django 5.2.9 on 2026-05-30 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0009_accidentprediction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccidentPrediction',
        ),
    ]
