# Generated by Django 5.2.3 on 2025-06-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_course_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
