# Generated by Django 5.1.6 on 2025-06-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_course_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
