# Generated by Django 5.1.6 on 2025-06-19 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_course_payment_status_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
    ]
