# Generated by Django 5.0.3 on 2025-06-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_course_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='job_images/'),
        ),
    ]
