# Generated by Django 5.0.3 on 2025-06-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_job_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
