# Generated by Django 5.0.3 on 2025-06-20 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_client_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.CharField(blank=True, max_length=10, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=100, null=True)),
                ('fav_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('ten_mark', models.CharField(max_length=200, null=True)),
                ('mark', models.CharField(max_length=200, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200, null=True)),
                ('rating', models.CharField(max_length=200, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
        ),
    ]
