# Generated by Django 5.0.3 on 2025-06-20 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_clientinterest_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
    ]
