# Generated by Django 5.1.4 on 2026-02-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='viewpassword',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
