# Generated by Django 5.1.6 on 2026-02-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_jobapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='status',
            field=models.CharField(default='Applied', max_length=20),
        ),
    ]
