# Generated by Django 5.1.6 on 2026-02-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_jobfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfeedback',
            name='rating',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
