# Generated by Django 5.1.6 on 2026-02-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='course',
            name='payment_status',
        ),
    ]
