# Generated by Django 5.1.6 on 2026-02-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_course_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
