# Generated by Django 5.1.6 on 2026-02-17 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
    ]
