# Generated by Django 5.1.6 on 2026-03-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_course_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to='tutor_certifications/'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='tutor_proofs/'),
        ),
    ]
