# Generated by Django 5.1.6 on 2026-03-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_tutor_certification_tutor_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='certitication',
            field=models.FileField(blank=True, null=True, upload_to='company_certifications/'),
        ),
        migrations.AddField(
            model_name='company',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='company_proofs/'),
        ),
    ]
