# Generated by Django 5.1.6 on 2026-03-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_company_certitication_company_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='certitication',
        ),
    ]
