# Generated by Django 5.1.6 on 2026-03-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_company_certitication'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to='company_certifications/'),
        ),
    ]
