# Generated by Django 5.1.6 on 2026-03-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
