# Generated by Django 5.1.6 on 2026-03-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_chat_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
