# Generated by Django 5.1.6 on 2026-03-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('fulltime', 'Full Time'), ('parttime', 'Part Time')], default='fulltime', max_length=20),
        ),
    ]
