# Generated by Django 5.1.6 on 2026-03-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
