# Generated by Django 5.1.1 on 2025-03-19 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0003_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.amount')),
            ],
        ),
    ]
