# Generated by Django 5.1.1 on 2025-03-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0005_slot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.customer')),
            ],
        ),
    ]
