# Generated by Django 5.2.16 on 2026-07-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0004_alter_predictionhistory_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionhistory',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='prediction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
