# Generated by Django 5.0.3 on 2024-03-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModule',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_email', models.CharField(max_length=100)),
                ('l_pass', models.CharField(max_length=100)),
                ('l_type', models.CharField(max_length=100)),
                ('l_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('u_fullname', models.CharField(max_length=100)),
                ('u_email', models.CharField(max_length=100)),
                ('u_phone', models.CharField(max_length=100)),
                ('u_address', models.CharField(max_length=100)),
                ('u_pass', models.CharField(max_length=100)),
                ('u_status', models.CharField(max_length=100)),
                ('u_profile', models.CharField(max_length=100)),
                ('u_about', models.CharField(max_length=100)),
                ('u_from', models.CharField(max_length=100)),
                ('u_work', models.CharField(max_length=100)),
                ('profile_image', models.FileField(upload_to='')),
                ('post_image', models.FileField(upload_to='')),
                ('u1', models.CharField(default='', max_length=100)),
                ('u2', models.CharField(default='', max_length=100)),
                ('u3', models.CharField(default='', max_length=100)),
                ('u4', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
