# Generated by Django 5.0.3 on 2024-03-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userregister_u_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_desc', models.CharField(max_length=100)),
                ('post_image', models.FileField(upload_to='')),
                ('post_type', models.CharField(max_length=100)),
                ('post_status', models.CharField(max_length=100)),
                ('u5', models.CharField(default='', max_length=100)),
                ('u6', models.CharField(default='', max_length=100)),
                ('u7', models.CharField(default='', max_length=100)),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userregister')),
            ],
        ),
    ]
