# Generated by Django 5.0.3 on 2024-03-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_addpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='u5',
            field=models.CharField(default='normal', max_length=100),
        ),
    ]
