# Generated by Django 5.0.3 on 2024-03-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_addpost_u5'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTaker',
            fields=[
                ('care_id', models.AutoField(primary_key=True, serialize=False)),
                ('care_fullname', models.CharField(max_length=100)),
                ('care_email', models.CharField(max_length=100)),
                ('care_phone', models.CharField(max_length=100)),
                ('care_address', models.CharField(max_length=100)),
                ('care_pass', models.CharField(max_length=100)),
                ('care_status', models.CharField(default='pending', max_length=100)),
                ('care_profile', models.CharField(max_length=100)),
                ('care_image', models.FileField(upload_to='')),
                ('u8', models.CharField(default='', max_length=100)),
                ('u9', models.CharField(default='', max_length=100)),
                ('u10', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
