# Generated by Django 5.0.3 on 2024-03-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_name', models.CharField(max_length=100)),
                ('feed_email', models.CharField(max_length=100)),
                ('saysomething', models.CharField(max_length=100)),
                ('f_status', models.CharField(max_length=100)),
                ('u11', models.CharField(default='', max_length=100)),
                ('u12', models.CharField(default='', max_length=100)),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userregister')),
            ],
        ),
    ]
