# Generated by Django 5.0.3 on 2024-03-18 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=100)),
                ('card_name', models.CharField(max_length=100)),
                ('exp_date', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
                ('b_status', models.CharField(default='pending', max_length=100)),
                ('u13', models.CharField(default='', max_length=100)),
                ('u14', models.CharField(default='', max_length=100)),
                ('u15', models.CharField(default='', max_length=100)),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userregister')),
            ],
        ),
    ]
