# Generated by Django 5.0.3 on 2024-03-18 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='care_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.caretaker'),
        ),
    ]
