# Generated by Django 5.2.11 on 2026-02-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0003_alter_driver_daddress_alter_driver_dcontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
