# Generated by Django 5.2.11 on 2026-02-24 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0004_booking_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textapp.booking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textapp.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textapp.user')),
            ],
        ),
    ]
