# Generated by Django 5.2.9 on 2025-12-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeriodUser',
            new_name='User_profile',
        ),
    ]
