# Generated by Django 5.2.9 on 2026-01-03 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_periodlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_profile'),
        ),
    ]
