# Generated by Django 5.2.9 on 2026-01-03 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_periodlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietRemedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Diet', 'Diet'), ('Remedy', 'Remedy')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hairfall', models.BooleanField(default=False)),
                ('acne', models.BooleanField(default=False)),
                ('pain', models.BooleanField(default=False)),
                ('mood_swings', models.BooleanField(default=False)),
                ('fatigue', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_profile')),
            ],
        ),
    ]
