# Generated by Django 5.0.3 on 2026-01-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='doctor_images/'),
        ),
    ]
