# Generated by Django 5.2.9 on 2026-03-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_doctor_license_document_doctor_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='appointment_reports/'),
        ),
    ]
