# Generated by Django 5.2.11 on 2026-03-03 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_app', '0002_doctor_experience_doctor_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('consultation_fee', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_app.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_app.user')),
            ],
        ),
    ]
