# Generated by Django 5.0.3 on 2026-03-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_app', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeukemiaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leukemia/')),
                ('result', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
