# Generated by Django 5.1.6 on 2025-02-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_delete_userreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='pharmacy_license_number',
        ),
        migrations.AddField(
            model_name='doctor',
            name='medical_license_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
