# Generated by Django 5.1.6 on 2025-02-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacist',
            name='pharmacy_license_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='pharmacy_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
