# Generated by Django 5.1.6 on 2025-02-20 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_pharmacist_pharmacy_license_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.IntegerField()),
                ('image', models.FileField(null=True, upload_to='profile')),
                ('date', models.DateField(null=True)),
                ('expiry', models.DateField(null=True)),
                ('side_effects', models.CharField(max_length=255, null=True)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.pharmacist')),
            ],
        ),
    ]
