# Generated by Django 5.1.6 on 2025-02-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='in_cart', max_length=50)),
                ('qty', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('Pharmacist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.pharmacist')),
                ('mid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.medicine')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
