# Generated by Django 5.1.6 on 2025-02-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_medicineorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='orginal_Price',
            field=models.IntegerField(null=True),
        ),
    ]
