# Generated by Django 5.1.6 on 2025-02-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_medicine_orginal_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=20, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('medicine_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicineorder')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pharmacist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
