# Generated by Django 5.1.6 on 2025-02-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
