# Generated by Django 5.2.4 on 2025-08-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitpal_app', '0004_planupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanUpload',
        ),
    ]
