# Generated by Django 4.2.7 on 2025-08-25 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitpal_app', '0008_userdietprogram_userstepprogress_healthmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.CharField(max_length=100)),
                ('utype', models.CharField(max_length=100)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitpal_app.userdetail')),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitpal_app.expertdetail')),
            ],
        ),
    ]
