# Generated by Django 4.2.7 on 2025-08-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitpal_app', '0012_dietfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietFeedback',
        ),
    ]
