# Generated by Django 5.1.4 on 2026-02-11 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitpal_app', '0017_dieticiandetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='diet_plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dietician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(max_length=100)),
                ('step_description', models.TextField()),
                ('step_image', models.ImageField(blank=True, null=True, upload_to='diet_steps/')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitpal_app.nutritionplan')),
            ],
        ),
    ]
