# Generated by Django 5.1.4 on 2026-02-12 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitpal_app', '0020_stepcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieticianChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.CharField(max_length=100)),
                ('utype', models.CharField(max_length=20)),
                ('dietician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitpal_app.dieticiandetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitpal_app.userdetail')),
            ],
        ),
    ]
