# Generated by Django 5.1.4 on 2025-01-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_owner_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=150, null=True)),
                ('location', models.CharField(max_length=150, null=True)),
                ('contact_number', models.CharField(max_length=15, null=True)),
                ('licence_number', models.CharField(max_length=15, null=True)),
                ('operating_hours', models.CharField(max_length=100, null=True)),
                ('charging_types', models.CharField(max_length=200, null=True)),
                ('image', models.FileField(null=True, upload_to='file')),
                ('price', models.CharField(max_length=50, null=True)),
                ('waiting_area', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.owner')),
            ],
        ),
    ]
