# Generated by Django 5.1.4 on 2025-01-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_payment_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comments',
            new_name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
