# Generated by Django 5.0.7 on 2025-03-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
