# Generated by Django 5.0.7 on 2025-03-06 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_payment_qr_image_payment_receipt_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='station',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.booking'),
        ),
    ]
