# Generated by Django 4.1.2 on 2024-01-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='image',
            field=models.FileField(default='image', upload_to='profile'),
        ),
    ]
