# Generated by Django 4.1.2 on 2024-01-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userreg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
