# Generated by Django 4.1.2 on 2024-01-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='location',
            field=models.CharField(blank=True, default='No location', max_length=100, null=True),
        ),
    ]
