# Generated by Django 4.1.2 on 2024-02-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
