# Generated by Django 4.1.2 on 2024-02-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_chat_content_type_chat_file_alter_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File')], default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='posts')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userreg')),
            ],
        ),
    ]
