# Generated by Django 4.1.2 on 2024-02-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_friends_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends_list',
            old_name='user2',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='friends_list',
            old_name='user1',
            new_name='user',
        ),
    ]
