# Generated by Django 4.2.3 on 2024-02-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_user2_friends_list_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.CharField(default='good', max_length=50),
        ),
    ]
