# Generated by Django 5.2.12 on 2026-04-06 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_chat_sender_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='sender_admin',
        ),
        migrations.CreateModel(
            name='AdminChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('content_type', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userreg')),
                ('sender_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
