# Generated by Django 5.2.12 on 2026-04-07 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_chat_sender_admin_adminchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminchat',
            name='receiver_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminchat',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userreg'),
        ),
        migrations.AlterField(
            model_name='adminchat',
            name='receiver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_received', to='myapp.userreg'),
        ),
        migrations.AlterField(
            model_name='adminchat',
            name='sender_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
